# Generated by Django 4.1.6 on 2023-04-02 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Slots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('floor', models.CharField(max_length=200)),
                ('slot_available', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownername', models.CharField(max_length=50)),
                ('ownercontact', models.CharField(max_length=15)),
                ('vehiclecatogary', models.CharField(max_length=20)),
                ('vehiclename', models.CharField(max_length=20)),
                ('registration_no', models.CharField(max_length=10)),
                ('parkingtoken', models.IntegerField()),
                ('park_date', models.DateField(auto_now_add=True)),
                ('intime', models.TimeField(auto_now_add=True)),
                ('payment', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
