# Generated by Django 4.1.7 on 2023-04-07 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='parking_fees',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
