# Generated by Django 4.1.6 on 2023-04-02 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='slot',
            field=models.ForeignKey(blank=True, max_length=200, null=True, on_delete=django.db.models.deletion.SET_NULL, to='park.slots'),
        ),
        migrations.CreateModel(
            name='Registerdcustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownername', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='park.customer')),
                ('slot', models.ForeignKey(blank=True, max_length=200, null=True, on_delete=django.db.models.deletion.SET_NULL, to='park.slots')),
            ],
        ),
    ]
